name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend-cd.yaml"

  workflow_dispatch:

jobs:

  lint:
    name: Frontend Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint


  test:
    name: Frontend Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: CI=true npm test


  build:
    name: Build and Push Frontend
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: starter/frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
          IMAGE_TAG: ${{ github.sha }}
          MOVIE_API_URL: ${{ secrets.REACT_APP_MOVIE_API_URL }}
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="$MOVIE_API_URL" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


  deploy:
    name: Deploy Frontend to EKS
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name cluster

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update frontend image
        working-directory: starter/frontend/k8s
        run: |
          kustomize edit set image \
            frontend=477803273608.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}

      - name: Deploy frontend
        working-directory: starter/frontend/k8s
        run: |
          kustomize build | kubectl apply -f -

      - name: Verify frontend deployment
        run: |
          kubectl rollout status deployment/frontend --timeout=5m